// Generated by rstantools.  Do not edit by hand.

/*
    intervalpsych is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    intervalpsych is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with intervalpsych.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.35.0-100-g96e409a
#include <stan/model/model_header.hpp>
namespace model_ddrm_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 66> locations_array__ =
  {" (found before start of program)",
  " (in 'string', line 18, column 2 to column 18)",
  " (in 'string', line 19, column 2 to column 16)",
  " (in 'string', line 21, column 2 to column 27)",
  " (in 'string', line 24, column 2 to column 20)",
  " (in 'string', line 25, column 2 to column 29)",
  " (in 'string', line 27, column 2 to column 17)",
  " (in 'string', line 28, column 2 to column 23)",
  " (in 'string', line 30, column 2 to column 29)",
  " (in 'string', line 35, column 2 to column 60)",
  " (in 'string', line 36, column 2 to column 60)",
  " (in 'string', line 37, column 2 to column 59)",
  " (in 'string', line 70, column 2 to column 20)",
  " (in 'string', line 72, column 2 to column 27)",
  " (in 'string', line 73, column 2 to column 29)",
  " (in 'string', line 77, column 4 to column 23)",
  " (in 'string', line 78, column 4 to column 80)",
  " (in 'string', line 79, column 4 to column 76)",
  " (in 'string', line 80, column 4 to column 80)",
  " (in 'string', line 82, column 4 to column 49)",
  " (in 'string', line 84, column 4 to column 39)",
  " (in 'string', line 85, column 4 to column 47)",
  " (in 'string', line 86, column 4 to column 47)",
  " (in 'string', line 87, column 4 to column 47)",
  " (in 'string', line 76, column 15 to line 88, column 3)",
  " (in 'string', line 76, column 2 to line 88, column 3)",
  " (in 'string', line 75, column 1 to line 89, column 2)",
  " (in 'string', line 42, column 2 to column 24)",
  " (in 'string', line 43, column 2 to column 24)",
  " (in 'string', line 45, column 2 to column 28)",
  " (in 'string', line 48, column 2 to column 34)",
  " (in 'string', line 49, column 2 to column 34)",
  " (in 'string', line 51, column 2 to column 31)",
  " (in 'string', line 52, column 2 to column 31)",
  " (in 'string', line 53, column 2 to column 31)",
  " (in 'string', line 56, column 8 to column 9)",
  " (in 'string', line 56, column 2 to column 30)",
  " (in 'string', line 58, column 4 to column 82)",
  " (in 'string', line 59, column 4 to column 78)",
  " (in 'string', line 60, column 4 to column 82)",
  " (in 'string', line 57, column 17 to line 61, column 3)",
  " (in 'string', line 57, column 4 to line 61, column 3)",
  " (in 'string', line 63, column 4 to column 36)",
  " (in 'string', line 55, column 2 to line 64, column 3)",
  " (in 'string', line 6, column 2 to column 17)",
  " (in 'string', line 7, column 2 to column 17)",
  " (in 'string', line 8, column 2 to column 17)",
  " (in 'string', line 9, column 2 to column 17)",
  " (in 'string', line 10, column 8 to column 9)",
  " (in 'string', line 10, column 2 to column 27)",
  " (in 'string', line 11, column 8 to column 9)",
  " (in 'string', line 11, column 2 to column 27)",
  " (in 'string', line 12, column 8 to column 9)",
  " (in 'string', line 12, column 2 to column 27)",
  " (in 'string', line 13, column 8 to column 9)",
  " (in 'string', line 13, column 2 to column 24)",
  " (in 'string', line 18, column 9 to column 10)",
  " (in 'string', line 19, column 9 to column 10)",
  " (in 'string', line 24, column 9 to column 10)",
  " (in 'string', line 25, column 18 to column 19)",
  " (in 'string', line 35, column 9 to column 10)",
  " (in 'string', line 36, column 9 to column 10)",
  " (in 'string', line 37, column 18 to column 19)",
  " (in 'string', line 70, column 9 to column 10)",
  " (in 'string', line 72, column 8 to column 9)",
  " (in 'string', line 73, column 8 to column 9)"};
#include <stan_meta_header.hpp>
class model_ddrm final : public model_base_crtp<model_ddrm> {
private:
  int I;
  int J;
  int K;
  int N;
  std::vector<int> ii;
  std::vector<int> jj;
  std::vector<int> nn;
  std::vector<Eigen::Matrix<double,-1,1>> Y;
public:
  ~model_ddrm() {}
  model_ddrm(stan::io::var_context& context__, unsigned int
             random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    using local_scalar_t__ = double;
    auto base_rng__ = stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_ddrm_namespace::model_ddrm";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 44;
      context__.validate_dims("data initialization", "I", "int",
        std::vector<size_t>{});
      I = std::numeric_limits<int>::min();
      current_statement__ = 44;
      I = context__.vals_i("I")[(1 - 1)];
      current_statement__ = 44;
      stan::math::check_greater_or_equal(function__, "I", I, 1);
      current_statement__ = 45;
      context__.validate_dims("data initialization", "J", "int",
        std::vector<size_t>{});
      J = std::numeric_limits<int>::min();
      current_statement__ = 45;
      J = context__.vals_i("J")[(1 - 1)];
      current_statement__ = 45;
      stan::math::check_greater_or_equal(function__, "J", J, 1);
      current_statement__ = 46;
      context__.validate_dims("data initialization", "K", "int",
        std::vector<size_t>{});
      K = std::numeric_limits<int>::min();
      current_statement__ = 46;
      K = context__.vals_i("K")[(1 - 1)];
      current_statement__ = 46;
      stan::math::check_greater_or_equal(function__, "K", K, 1);
      current_statement__ = 47;
      context__.validate_dims("data initialization", "N", "int",
        std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      current_statement__ = 47;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 47;
      stan::math::check_greater_or_equal(function__, "N", N, 1);
      current_statement__ = 48;
      stan::math::validate_non_negative_index("ii", "N", N);
      current_statement__ = 49;
      context__.validate_dims("data initialization", "ii", "int",
        std::vector<size_t>{static_cast<size_t>(N)});
      ii = std::vector<int>(N, std::numeric_limits<int>::min());
      current_statement__ = 49;
      ii = context__.vals_i("ii");
      current_statement__ = 49;
      stan::math::check_greater_or_equal(function__, "ii", ii, 1);
      current_statement__ = 50;
      stan::math::validate_non_negative_index("jj", "N", N);
      current_statement__ = 51;
      context__.validate_dims("data initialization", "jj", "int",
        std::vector<size_t>{static_cast<size_t>(N)});
      jj = std::vector<int>(N, std::numeric_limits<int>::min());
      current_statement__ = 51;
      jj = context__.vals_i("jj");
      current_statement__ = 51;
      stan::math::check_greater_or_equal(function__, "jj", jj, 1);
      current_statement__ = 52;
      stan::math::validate_non_negative_index("nn", "N", N);
      current_statement__ = 53;
      context__.validate_dims("data initialization", "nn", "int",
        std::vector<size_t>{static_cast<size_t>(N)});
      nn = std::vector<int>(N, std::numeric_limits<int>::min());
      current_statement__ = 53;
      nn = context__.vals_i("nn");
      current_statement__ = 53;
      stan::math::check_greater_or_equal(function__, "nn", nn, 1);
      current_statement__ = 54;
      stan::math::validate_non_negative_index("Y", "N", N);
      current_statement__ = 55;
      context__.validate_dims("data initialization", "Y", "double",
        std::vector<size_t>{static_cast<size_t>(N), static_cast<size_t>(3)});
      Y = std::vector<Eigen::Matrix<double,-1,1>>(N,
            Eigen::Matrix<double,-1,1>::Constant(3,
              std::numeric_limits<double>::quiet_NaN()));
      {
        std::vector<local_scalar_t__> Y_flat__;
        current_statement__ = 55;
        Y_flat__ = context__.vals_r("Y");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= 3; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            stan::model::assign(Y, Y_flat__[(pos__ - 1)],
              "assigning variable Y", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 55;
      stan::math::check_simplex(function__, "Y", Y);
      current_statement__ = 56;
      stan::math::validate_non_negative_index("theta", "I", I);
      current_statement__ = 57;
      stan::math::validate_non_negative_index("eta", "I", I);
      current_statement__ = 58;
      stan::math::validate_non_negative_index("J_raw", "J", J);
      current_statement__ = 59;
      stan::math::validate_non_negative_index("tau_raw", "J", J);
      current_statement__ = 60;
      stan::math::validate_non_negative_index("delta", "J", J);
      current_statement__ = 61;
      stan::math::validate_non_negative_index("gamma", "J", J);
      current_statement__ = 62;
      stan::math::validate_non_negative_index("tau", "J", J);
      current_statement__ = 63;
      stan::math::validate_non_negative_index("log_lik", "N", N);
      current_statement__ = 64;
      stan::math::validate_non_negative_index("Y_rep", "N", N);
      current_statement__ = 65;
      stan::math::validate_non_negative_index("Y_e_rep", "N", N);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = I + I + 2 + (J * 2) + J + 2 + 1 + 3;
  }
  inline std::string model_name() const final {
    return "model_ddrm";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.35.0-100-g96e409a",
             "stancflags = --allow-undefined"};
  }
  // Base log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_not_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_ddrm_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      current_statement__ = 1;
      auto theta =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(I);
      current_statement__ = 2;
      auto eta = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(I);
      current_statement__ = 3;
      auto alpha =
        in__.template read_constrain_lb<Eigen::Matrix<local_scalar_t__,-1,1>,
          jacobian__>(0, lp__, 2);
      current_statement__ = 4;
      auto J_raw =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,-1>>(J, 2);
      current_statement__ = 5;
      auto tau_raw =
        in__.template read_constrain_lb<Eigen::Matrix<local_scalar_t__,-1,1>,
          jacobian__>(0, lp__, J);
      current_statement__ = 6;
      auto mu_J = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(2);
      current_statement__ = 7;
      auto mu_tau =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      current_statement__ = 8;
      auto sigma_J =
        in__.template read_constrain_lb<Eigen::Matrix<local_scalar_t__,-1,1>,
          jacobian__>(0, lp__, 3);
      Eigen::Matrix<local_scalar_t__,-1,1> delta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      current_statement__ = 9;
      stan::model::assign(delta,
        stan::math::add(
          stan::math::multiply(
            stan::model::rvalue(J_raw, "J_raw", stan::model::index_omni(),
              stan::model::index_uni(1)),
            stan::model::rvalue(sigma_J, "sigma_J", stan::model::index_uni(1))),
          stan::model::rvalue(mu_J, "mu_J", stan::model::index_uni(1))),
        "assigning variable delta");
      Eigen::Matrix<local_scalar_t__,-1,1> gamma =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      current_statement__ = 10;
      stan::model::assign(gamma,
        stan::math::add(
          stan::math::multiply(
            stan::model::rvalue(J_raw, "J_raw", stan::model::index_omni(),
              stan::model::index_uni(2)),
            stan::model::rvalue(sigma_J, "sigma_J", stan::model::index_uni(2))),
          stan::model::rvalue(mu_J, "mu_J", stan::model::index_uni(2))),
        "assigning variable gamma");
      Eigen::Matrix<local_scalar_t__,-1,1> tau =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      current_statement__ = 11;
      stan::model::assign(tau,
        stan::math::add(
          stan::math::multiply(tau_raw,
            stan::model::rvalue(sigma_J, "sigma_J", stan::model::index_uni(3))),
          mu_tau), "assigning variable tau");
      current_statement__ = 11;
      stan::math::check_greater_or_equal(function__, "tau", tau, 0);
      {
        current_statement__ = 27;
        lp_accum__.add(stan::math::std_normal_lpdf<propto__>(theta));
        current_statement__ = 28;
        lp_accum__.add(stan::math::std_normal_lpdf<propto__>(eta));
        current_statement__ = 29;
        lp_accum__.add(stan::math::student_t_lpdf<propto__>(alpha, 3, 0, 1));
        current_statement__ = 30;
        lp_accum__.add(stan::math::std_normal_lpdf<propto__>(
                         stan::math::to_vector(J_raw)));
        current_statement__ = 31;
        lp_accum__.add(stan::math::std_normal_lpdf<propto__>(tau_raw));
        current_statement__ = 32;
        lp_accum__.add(stan::math::student_t_lpdf<propto__>(mu_J, 3, 0, 2));
        current_statement__ = 33;
        lp_accum__.add(stan::math::student_t_lpdf<propto__>(mu_tau, 3, 0, 1));
        current_statement__ = 34;
        lp_accum__.add(stan::math::student_t_lpdf<propto__>(sigma_J, 3, 0, 1));
        {
          current_statement__ = 35;
          stan::math::validate_non_negative_index("pars_dir", "N", N);
          std::vector<Eigen::Matrix<local_scalar_t__,-1,1>> pars_dir =
            std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>(N,
              Eigen::Matrix<local_scalar_t__,-1,1>::Constant(3, DUMMY_VAR__));
          current_statement__ = 41;
          for (int n = 1; n <= N; ++n) {
            current_statement__ = 37;
            stan::model::assign(pars_dir,
              stan::math::exp(
                ((stan::model::rvalue(alpha, "alpha",
                    stan::model::index_uni(1)) *
                (stan::model::rvalue(theta, "theta",
                   stan::model::index_uni(
                     stan::model::rvalue(ii, "ii", stan::model::index_uni(n))))
                -
                stan::model::rvalue(delta, "delta",
                  stan::model::index_uni(
                    stan::model::rvalue(jj, "jj", stan::model::index_uni(n))))))
                +
                stan::model::rvalue(tau, "tau",
                  stan::model::index_uni(
                    stan::model::rvalue(jj, "jj", stan::model::index_uni(n)))))),
              "assigning variable pars_dir", stan::model::index_uni(n),
              stan::model::index_uni(1));
            current_statement__ = 38;
            stan::model::assign(pars_dir,
              stan::math::exp(
                ((stan::model::rvalue(alpha, "alpha",
                    stan::model::index_uni(2)) *
                (stan::model::rvalue(eta, "eta",
                   stan::model::index_uni(
                     stan::model::rvalue(ii, "ii", stan::model::index_uni(n))))
                +
                stan::model::rvalue(gamma, "gamma",
                  stan::model::index_uni(
                    stan::model::rvalue(jj, "jj", stan::model::index_uni(n))))))
                +
                stan::model::rvalue(tau, "tau",
                  stan::model::index_uni(
                    stan::model::rvalue(jj, "jj", stan::model::index_uni(n)))))),
              "assigning variable pars_dir", stan::model::index_uni(n),
              stan::model::index_uni(2));
            current_statement__ = 39;
            stan::model::assign(pars_dir,
              stan::math::exp(
                ((-(stan::model::rvalue(alpha, "alpha",
                      stan::model::index_uni(1))) *
                (stan::model::rvalue(theta, "theta",
                   stan::model::index_uni(
                     stan::model::rvalue(ii, "ii", stan::model::index_uni(n))))
                -
                stan::model::rvalue(delta, "delta",
                  stan::model::index_uni(
                    stan::model::rvalue(jj, "jj", stan::model::index_uni(n))))))
                +
                stan::model::rvalue(tau, "tau",
                  stan::model::index_uni(
                    stan::model::rvalue(jj, "jj", stan::model::index_uni(n)))))),
              "assigning variable pars_dir", stan::model::index_uni(n),
              stan::model::index_uni(3));
          }
          current_statement__ = 42;
          lp_accum__.add(stan::math::dirichlet_lpdf<propto__>(
                           stan::model::rvalue(Y, "Y",
                             stan::model::index_multi(nn)),
                           stan::model::rvalue(pars_dir, "pars_dir",
                             stan::model::index_multi(nn))));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  // Reverse mode autodiff log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_ddrm_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      current_statement__ = 1;
      auto theta =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(I);
      current_statement__ = 2;
      auto eta = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(I);
      current_statement__ = 3;
      auto alpha =
        in__.template read_constrain_lb<Eigen::Matrix<local_scalar_t__,-1,1>,
          jacobian__>(0, lp__, 2);
      current_statement__ = 4;
      auto J_raw =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,-1>>(J, 2);
      current_statement__ = 5;
      auto tau_raw =
        in__.template read_constrain_lb<Eigen::Matrix<local_scalar_t__,-1,1>,
          jacobian__>(0, lp__, J);
      current_statement__ = 6;
      auto mu_J = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(2);
      current_statement__ = 7;
      auto mu_tau =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      current_statement__ = 8;
      auto sigma_J =
        in__.template read_constrain_lb<Eigen::Matrix<local_scalar_t__,-1,1>,
          jacobian__>(0, lp__, 3);
      Eigen::Matrix<local_scalar_t__,-1,1> delta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      current_statement__ = 9;
      stan::model::assign(delta,
        stan::math::add(
          stan::math::multiply(
            stan::model::rvalue(J_raw, "J_raw", stan::model::index_omni(),
              stan::model::index_uni(1)),
            stan::model::rvalue(sigma_J, "sigma_J", stan::model::index_uni(1))),
          stan::model::rvalue(mu_J, "mu_J", stan::model::index_uni(1))),
        "assigning variable delta");
      Eigen::Matrix<local_scalar_t__,-1,1> gamma =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      current_statement__ = 10;
      stan::model::assign(gamma,
        stan::math::add(
          stan::math::multiply(
            stan::model::rvalue(J_raw, "J_raw", stan::model::index_omni(),
              stan::model::index_uni(2)),
            stan::model::rvalue(sigma_J, "sigma_J", stan::model::index_uni(2))),
          stan::model::rvalue(mu_J, "mu_J", stan::model::index_uni(2))),
        "assigning variable gamma");
      Eigen::Matrix<local_scalar_t__,-1,1> tau =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      current_statement__ = 11;
      stan::model::assign(tau,
        stan::math::add(
          stan::math::multiply(tau_raw,
            stan::model::rvalue(sigma_J, "sigma_J", stan::model::index_uni(3))),
          mu_tau), "assigning variable tau");
      current_statement__ = 11;
      stan::math::check_greater_or_equal(function__, "tau", tau, 0);
      {
        current_statement__ = 27;
        lp_accum__.add(stan::math::std_normal_lpdf<propto__>(theta));
        current_statement__ = 28;
        lp_accum__.add(stan::math::std_normal_lpdf<propto__>(eta));
        current_statement__ = 29;
        lp_accum__.add(stan::math::student_t_lpdf<propto__>(alpha, 3, 0, 1));
        current_statement__ = 30;
        lp_accum__.add(stan::math::std_normal_lpdf<propto__>(
                         stan::math::to_vector(J_raw)));
        current_statement__ = 31;
        lp_accum__.add(stan::math::std_normal_lpdf<propto__>(tau_raw));
        current_statement__ = 32;
        lp_accum__.add(stan::math::student_t_lpdf<propto__>(mu_J, 3, 0, 2));
        current_statement__ = 33;
        lp_accum__.add(stan::math::student_t_lpdf<propto__>(mu_tau, 3, 0, 1));
        current_statement__ = 34;
        lp_accum__.add(stan::math::student_t_lpdf<propto__>(sigma_J, 3, 0, 1));
        {
          current_statement__ = 35;
          stan::math::validate_non_negative_index("pars_dir", "N", N);
          std::vector<Eigen::Matrix<local_scalar_t__,-1,1>> pars_dir =
            std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>(N,
              Eigen::Matrix<local_scalar_t__,-1,1>::Constant(3, DUMMY_VAR__));
          current_statement__ = 41;
          for (int n = 1; n <= N; ++n) {
            current_statement__ = 37;
            stan::model::assign(pars_dir,
              stan::math::exp(
                ((stan::model::rvalue(alpha, "alpha",
                    stan::model::index_uni(1)) *
                (stan::model::rvalue(theta, "theta",
                   stan::model::index_uni(
                     stan::model::rvalue(ii, "ii", stan::model::index_uni(n))))
                -
                stan::model::rvalue(delta, "delta",
                  stan::model::index_uni(
                    stan::model::rvalue(jj, "jj", stan::model::index_uni(n))))))
                +
                stan::model::rvalue(tau, "tau",
                  stan::model::index_uni(
                    stan::model::rvalue(jj, "jj", stan::model::index_uni(n)))))),
              "assigning variable pars_dir", stan::model::index_uni(n),
              stan::model::index_uni(1));
            current_statement__ = 38;
            stan::model::assign(pars_dir,
              stan::math::exp(
                ((stan::model::rvalue(alpha, "alpha",
                    stan::model::index_uni(2)) *
                (stan::model::rvalue(eta, "eta",
                   stan::model::index_uni(
                     stan::model::rvalue(ii, "ii", stan::model::index_uni(n))))
                +
                stan::model::rvalue(gamma, "gamma",
                  stan::model::index_uni(
                    stan::model::rvalue(jj, "jj", stan::model::index_uni(n))))))
                +
                stan::model::rvalue(tau, "tau",
                  stan::model::index_uni(
                    stan::model::rvalue(jj, "jj", stan::model::index_uni(n)))))),
              "assigning variable pars_dir", stan::model::index_uni(n),
              stan::model::index_uni(2));
            current_statement__ = 39;
            stan::model::assign(pars_dir,
              stan::math::exp(
                ((-(stan::model::rvalue(alpha, "alpha",
                      stan::model::index_uni(1))) *
                (stan::model::rvalue(theta, "theta",
                   stan::model::index_uni(
                     stan::model::rvalue(ii, "ii", stan::model::index_uni(n))))
                -
                stan::model::rvalue(delta, "delta",
                  stan::model::index_uni(
                    stan::model::rvalue(jj, "jj", stan::model::index_uni(n))))))
                +
                stan::model::rvalue(tau, "tau",
                  stan::model::index_uni(
                    stan::model::rvalue(jj, "jj", stan::model::index_uni(n)))))),
              "assigning variable pars_dir", stan::model::index_uni(n),
              stan::model::index_uni(3));
          }
          current_statement__ = 42;
          lp_accum__.add(stan::math::dirichlet_lpdf<propto__>(
                           stan::model::rvalue(Y, "Y",
                             stan::model::index_multi(nn)),
                           stan::model::rvalue(pars_dir, "pars_dir",
                             stan::model::index_multi(nn))));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    // suppress unused var warning
    (void) jacobian__;
    static constexpr const char* function__ =
      "model_ddrm_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      current_statement__ = 1;
      auto theta =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(I);
      current_statement__ = 2;
      auto eta = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(I);
      current_statement__ = 3;
      auto alpha =
        in__.template read_constrain_lb<Eigen::Matrix<local_scalar_t__,-1,1>,
          jacobian__>(0, lp__, 2);
      current_statement__ = 4;
      auto J_raw =
        in__.template read<Eigen::Matrix<local_scalar_t__,-1,-1>>(J, 2);
      current_statement__ = 5;
      auto tau_raw =
        in__.template read_constrain_lb<Eigen::Matrix<local_scalar_t__,-1,1>,
          jacobian__>(0, lp__, J);
      current_statement__ = 6;
      auto mu_J = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(2);
      current_statement__ = 7;
      auto mu_tau =
        in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
          lp__);
      current_statement__ = 8;
      auto sigma_J =
        in__.template read_constrain_lb<Eigen::Matrix<local_scalar_t__,-1,1>,
          jacobian__>(0, lp__, 3);
      Eigen::Matrix<double,-1,1> delta =
        Eigen::Matrix<double,-1,1>::Constant(J,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> gamma =
        Eigen::Matrix<double,-1,1>::Constant(J,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> tau =
        Eigen::Matrix<double,-1,1>::Constant(J,
          std::numeric_limits<double>::quiet_NaN());
      out__.write(theta);
      out__.write(eta);
      out__.write(alpha);
      out__.write(J_raw);
      out__.write(tau_raw);
      out__.write(mu_J);
      out__.write(mu_tau);
      out__.write(sigma_J);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 9;
      stan::model::assign(delta,
        stan::math::add(
          stan::math::multiply(
            stan::model::rvalue(J_raw, "J_raw", stan::model::index_omni(),
              stan::model::index_uni(1)),
            stan::model::rvalue(sigma_J, "sigma_J", stan::model::index_uni(1))),
          stan::model::rvalue(mu_J, "mu_J", stan::model::index_uni(1))),
        "assigning variable delta");
      current_statement__ = 10;
      stan::model::assign(gamma,
        stan::math::add(
          stan::math::multiply(
            stan::model::rvalue(J_raw, "J_raw", stan::model::index_omni(),
              stan::model::index_uni(2)),
            stan::model::rvalue(sigma_J, "sigma_J", stan::model::index_uni(2))),
          stan::model::rvalue(mu_J, "mu_J", stan::model::index_uni(2))),
        "assigning variable gamma");
      current_statement__ = 11;
      stan::model::assign(tau,
        stan::math::add(
          stan::math::multiply(tau_raw,
            stan::model::rvalue(sigma_J, "sigma_J", stan::model::index_uni(3))),
          mu_tau), "assigning variable tau");
      current_statement__ = 11;
      stan::math::check_greater_or_equal(function__, "tau", tau, 0);
      if (emit_transformed_parameters__) {
        out__.write(delta);
        out__.write(gamma);
        out__.write(tau);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
      Eigen::Matrix<double,-1,1> log_lik =
        Eigen::Matrix<double,-1,1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      std::vector<Eigen::Matrix<double,-1,1>> Y_rep =
        std::vector<Eigen::Matrix<double,-1,1>>(N,
          Eigen::Matrix<double,-1,1>::Constant(3,
            std::numeric_limits<double>::quiet_NaN()));
      std::vector<Eigen::Matrix<double,-1,1>> Y_e_rep =
        std::vector<Eigen::Matrix<double,-1,1>>(N,
          Eigen::Matrix<double,-1,1>::Constant(3,
            std::numeric_limits<double>::quiet_NaN()));
      {
        current_statement__ = 25;
        for (int n = 1; n <= N; ++n) {
          Eigen::Matrix<double,-1,1> pars_dir =
            Eigen::Matrix<double,-1,1>::Constant(3,
              std::numeric_limits<double>::quiet_NaN());
          current_statement__ = 16;
          stan::model::assign(pars_dir,
            stan::math::exp(
              ((stan::model::rvalue(alpha, "alpha", stan::model::index_uni(1))
              *
              (stan::model::rvalue(theta, "theta",
                 stan::model::index_uni(
                   stan::model::rvalue(ii, "ii", stan::model::index_uni(n))))
              -
              stan::model::rvalue(delta, "delta",
                stan::model::index_uni(
                  stan::model::rvalue(jj, "jj", stan::model::index_uni(n))))))
              +
              stan::model::rvalue(tau, "tau",
                stan::model::index_uni(
                  stan::model::rvalue(jj, "jj", stan::model::index_uni(n)))))),
            "assigning variable pars_dir", stan::model::index_uni(1));
          current_statement__ = 17;
          stan::model::assign(pars_dir,
            stan::math::exp(
              ((stan::model::rvalue(alpha, "alpha", stan::model::index_uni(2))
              *
              (stan::model::rvalue(eta, "eta",
                 stan::model::index_uni(
                   stan::model::rvalue(ii, "ii", stan::model::index_uni(n))))
              +
              stan::model::rvalue(gamma, "gamma",
                stan::model::index_uni(
                  stan::model::rvalue(jj, "jj", stan::model::index_uni(n))))))
              +
              stan::model::rvalue(tau, "tau",
                stan::model::index_uni(
                  stan::model::rvalue(jj, "jj", stan::model::index_uni(n)))))),
            "assigning variable pars_dir", stan::model::index_uni(2));
          current_statement__ = 18;
          stan::model::assign(pars_dir,
            stan::math::exp(
              ((-(stan::model::rvalue(alpha, "alpha",
                    stan::model::index_uni(1))) *
              (stan::model::rvalue(theta, "theta",
                 stan::model::index_uni(
                   stan::model::rvalue(ii, "ii", stan::model::index_uni(n))))
              -
              stan::model::rvalue(delta, "delta",
                stan::model::index_uni(
                  stan::model::rvalue(jj, "jj", stan::model::index_uni(n))))))
              +
              stan::model::rvalue(tau, "tau",
                stan::model::index_uni(
                  stan::model::rvalue(jj, "jj", stan::model::index_uni(n)))))),
            "assigning variable pars_dir", stan::model::index_uni(3));
          current_statement__ = 19;
          stan::model::assign(log_lik,
            stan::math::dirichlet_lpdf<false>(
              stan::model::rvalue(Y, "Y", stan::model::index_uni(n)),
              pars_dir), "assigning variable log_lik",
            stan::model::index_uni(n));
          current_statement__ = 20;
          stan::model::assign(Y_rep,
            stan::math::dirichlet_rng(pars_dir, base_rng__),
            "assigning variable Y_rep", stan::model::index_uni(n));
          current_statement__ = 21;
          stan::model::assign(Y_e_rep,
            (stan::model::rvalue(pars_dir, "pars_dir",
               stan::model::index_uni(1)) / stan::math::sum(pars_dir)),
            "assigning variable Y_e_rep", stan::model::index_uni(n),
            stan::model::index_uni(1));
          current_statement__ = 22;
          stan::model::assign(Y_e_rep,
            (stan::model::rvalue(pars_dir, "pars_dir",
               stan::model::index_uni(2)) / stan::math::sum(pars_dir)),
            "assigning variable Y_e_rep", stan::model::index_uni(n),
            stan::model::index_uni(2));
          current_statement__ = 23;
          stan::model::assign(Y_e_rep,
            (stan::model::rvalue(pars_dir, "pars_dir",
               stan::model::index_uni(3)) / stan::math::sum(pars_dir)),
            "assigning variable Y_e_rep", stan::model::index_uni(n),
            stan::model::index_uni(3));
        }
      }
      out__.write(log_lik);
      current_statement__ = 13;
      for (int sym1__ = 1; sym1__ <= 3; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
          out__.write(Y_rep[(sym2__ - 1)][(sym1__ - 1)]);
        }
      }
      current_statement__ = 14;
      for (int sym1__ = 1; sym1__ <= 3; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
          out__.write(Y_e_rep[(sym2__ - 1)][(sym1__ - 1)]);
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,1> theta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(I, DUMMY_VAR__);
      current_statement__ = 1;
      stan::model::assign(theta,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(I),
        "assigning variable theta");
      out__.write(theta);
      Eigen::Matrix<local_scalar_t__,-1,1> eta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(I, DUMMY_VAR__);
      current_statement__ = 2;
      stan::model::assign(eta,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(I),
        "assigning variable eta");
      out__.write(eta);
      Eigen::Matrix<local_scalar_t__,-1,1> alpha =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(2, DUMMY_VAR__);
      current_statement__ = 3;
      stan::model::assign(alpha,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(2),
        "assigning variable alpha");
      out__.write_free_lb(0, alpha);
      Eigen::Matrix<local_scalar_t__,-1,-1> J_raw =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(J, 2, DUMMY_VAR__);
      current_statement__ = 4;
      stan::model::assign(J_raw,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,-1>>(J, 2),
        "assigning variable J_raw");
      out__.write(J_raw);
      Eigen::Matrix<local_scalar_t__,-1,1> tau_raw =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      current_statement__ = 5;
      stan::model::assign(tau_raw,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(J),
        "assigning variable tau_raw");
      out__.write_free_lb(0, tau_raw);
      Eigen::Matrix<local_scalar_t__,-1,1> mu_J =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(2, DUMMY_VAR__);
      current_statement__ = 6;
      stan::model::assign(mu_J,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(2),
        "assigning variable mu_J");
      out__.write(mu_J);
      local_scalar_t__ mu_tau = DUMMY_VAR__;
      current_statement__ = 7;
      mu_tau = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, mu_tau);
      Eigen::Matrix<local_scalar_t__,-1,1> sigma_J =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(3, DUMMY_VAR__);
      current_statement__ = 8;
      stan::model::assign(sigma_J,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(3),
        "assigning variable sigma_J");
      out__.write_free_lb(0, sigma_J);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "theta", "double",
        std::vector<size_t>{static_cast<size_t>(I)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "eta", "double",
        std::vector<size_t>{static_cast<size_t>(I)});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "alpha", "double",
        std::vector<size_t>{static_cast<size_t>(2)});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "J_raw", "double",
        std::vector<size_t>{static_cast<size_t>(J), static_cast<size_t>(2)});
      current_statement__ = 5;
      context__.validate_dims("parameter initialization", "tau_raw",
        "double", std::vector<size_t>{static_cast<size_t>(J)});
      current_statement__ = 6;
      context__.validate_dims("parameter initialization", "mu_J", "double",
        std::vector<size_t>{static_cast<size_t>(2)});
      current_statement__ = 7;
      context__.validate_dims("parameter initialization", "mu_tau", "double",
        std::vector<size_t>{});
      current_statement__ = 8;
      context__.validate_dims("parameter initialization", "sigma_J",
        "double", std::vector<size_t>{static_cast<size_t>(3)});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> theta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(I, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> theta_flat__;
        current_statement__ = 1;
        theta_flat__ = context__.vals_r("theta");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= I; ++sym1__) {
          stan::model::assign(theta, theta_flat__[(pos__ - 1)],
            "assigning variable theta", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      out__.write(theta);
      Eigen::Matrix<local_scalar_t__,-1,1> eta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(I, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> eta_flat__;
        current_statement__ = 2;
        eta_flat__ = context__.vals_r("eta");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= I; ++sym1__) {
          stan::model::assign(eta, eta_flat__[(pos__ - 1)],
            "assigning variable eta", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      out__.write(eta);
      Eigen::Matrix<local_scalar_t__,-1,1> alpha =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(2, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> alpha_flat__;
        current_statement__ = 3;
        alpha_flat__ = context__.vals_r("alpha");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
          stan::model::assign(alpha, alpha_flat__[(pos__ - 1)],
            "assigning variable alpha", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_lb(0, alpha);
      Eigen::Matrix<local_scalar_t__,-1,-1> J_raw =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(J, 2, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> J_raw_flat__;
        current_statement__ = 4;
        J_raw_flat__ = context__.vals_r("J_raw");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= J; ++sym2__) {
            stan::model::assign(J_raw, J_raw_flat__[(pos__ - 1)],
              "assigning variable J_raw", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            pos__ = (pos__ + 1);
          }
        }
      }
      out__.write(J_raw);
      Eigen::Matrix<local_scalar_t__,-1,1> tau_raw =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> tau_raw_flat__;
        current_statement__ = 5;
        tau_raw_flat__ = context__.vals_r("tau_raw");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
          stan::model::assign(tau_raw, tau_raw_flat__[(pos__ - 1)],
            "assigning variable tau_raw", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_lb(0, tau_raw);
      Eigen::Matrix<local_scalar_t__,-1,1> mu_J =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(2, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> mu_J_flat__;
        current_statement__ = 6;
        mu_J_flat__ = context__.vals_r("mu_J");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
          stan::model::assign(mu_J, mu_J_flat__[(pos__ - 1)],
            "assigning variable mu_J", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      out__.write(mu_J);
      local_scalar_t__ mu_tau = DUMMY_VAR__;
      current_statement__ = 7;
      mu_tau = context__.vals_r("mu_tau")[(1 - 1)];
      out__.write_free_lb(0, mu_tau);
      Eigen::Matrix<local_scalar_t__,-1,1> sigma_J =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(3, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> sigma_J_flat__;
        current_statement__ = 8;
        sigma_J_flat__ = context__.vals_r("sigma_J");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= 3; ++sym1__) {
          stan::model::assign(sigma_J, sigma_J_flat__[(pos__ - 1)],
            "assigning variable sigma_J", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_lb(0, sigma_J);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"theta", "eta", "alpha", "J_raw",
                "tau_raw", "mu_J", "mu_tau", "sigma_J"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"delta", "gamma", "tau"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::string> temp{"log_lik", "Y_rep", "Y_e_rep"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(I)},
                std::vector<size_t>{static_cast<size_t>(I)},
                std::vector<size_t>{static_cast<size_t>(2)},
                std::vector<size_t>{static_cast<size_t>(J),
                  static_cast<size_t>(2)},
                std::vector<size_t>{static_cast<size_t>(J)},
                std::vector<size_t>{static_cast<size_t>(2)},
                std::vector<size_t>{},
                std::vector<size_t>{static_cast<size_t>(3)}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(J)},
             std::vector<size_t>{static_cast<size_t>(J)},
             std::vector<size_t>{static_cast<size_t>(J)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(N)},
             std::vector<size_t>{static_cast<size_t>(N),
               static_cast<size_t>(3)},
             std::vector<size_t>{static_cast<size_t>(N),
               static_cast<size_t>(3)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= I; ++sym1__) {
      param_names__.emplace_back(std::string() + "theta" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= I; ++sym1__) {
      param_names__.emplace_back(std::string() + "eta" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
      param_names__.emplace_back(std::string() + "alpha" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= J; ++sym2__) {
        param_names__.emplace_back(std::string() + "J_raw" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
      param_names__.emplace_back(std::string() + "tau_raw" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
      param_names__.emplace_back(std::string() + "mu_J" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "mu_tau");
    for (int sym1__ = 1; sym1__ <= 3; ++sym1__) {
      param_names__.emplace_back(std::string() + "sigma_J" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
        param_names__.emplace_back(std::string() + "delta" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
        param_names__.emplace_back(std::string() + "gamma" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
        param_names__.emplace_back(std::string() + "tau" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "log_lik" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= 3; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
          param_names__.emplace_back(std::string() + "Y_rep" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= 3; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
          param_names__.emplace_back(std::string() + "Y_e_rep" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
    }
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= I; ++sym1__) {
      param_names__.emplace_back(std::string() + "theta" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= I; ++sym1__) {
      param_names__.emplace_back(std::string() + "eta" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
      param_names__.emplace_back(std::string() + "alpha" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= J; ++sym2__) {
        param_names__.emplace_back(std::string() + "J_raw" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
      param_names__.emplace_back(std::string() + "tau_raw" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
      param_names__.emplace_back(std::string() + "mu_J" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "mu_tau");
    for (int sym1__ = 1; sym1__ <= 3; ++sym1__) {
      param_names__.emplace_back(std::string() + "sigma_J" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
        param_names__.emplace_back(std::string() + "delta" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
        param_names__.emplace_back(std::string() + "gamma" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
        param_names__.emplace_back(std::string() + "tau" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "log_lik" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= 3; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
          param_names__.emplace_back(std::string() + "Y_rep" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= 3; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
          param_names__.emplace_back(std::string() + "Y_e_rep" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
    }
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"theta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(I) + "},\"block\":\"parameters\"},{\"name\":\"eta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(I) + "},\"block\":\"parameters\"},{\"name\":\"alpha\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(2) + "},\"block\":\"parameters\"},{\"name\":\"J_raw\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(J) + ",\"cols\":" + std::to_string(2) + "},\"block\":\"parameters\"},{\"name\":\"tau_raw\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(J) + "},\"block\":\"parameters\"},{\"name\":\"mu_J\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(2) + "},\"block\":\"parameters\"},{\"name\":\"mu_tau\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_J\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(3) + "},\"block\":\"parameters\"},{\"name\":\"delta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(J) + "},\"block\":\"transformed_parameters\"},{\"name\":\"gamma\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(J) + "},\"block\":\"transformed_parameters\"},{\"name\":\"tau\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(J) + "},\"block\":\"transformed_parameters\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"},{\"name\":\"Y_rep\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(N) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string(3) + "}},\"block\":\"generated_quantities\"},{\"name\":\"Y_e_rep\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(N) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string(3) + "}},\"block\":\"generated_quantities\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"theta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(I) + "},\"block\":\"parameters\"},{\"name\":\"eta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(I) + "},\"block\":\"parameters\"},{\"name\":\"alpha\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(2) + "},\"block\":\"parameters\"},{\"name\":\"J_raw\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(J) + ",\"cols\":" + std::to_string(2) + "},\"block\":\"parameters\"},{\"name\":\"tau_raw\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(J) + "},\"block\":\"parameters\"},{\"name\":\"mu_J\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(2) + "},\"block\":\"parameters\"},{\"name\":\"mu_tau\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_J\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(3) + "},\"block\":\"parameters\"},{\"name\":\"delta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(J) + "},\"block\":\"transformed_parameters\"},{\"name\":\"gamma\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(J) + "},\"block\":\"transformed_parameters\"},{\"name\":\"tau\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(J) + "},\"block\":\"transformed_parameters\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"},{\"name\":\"Y_rep\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(N) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string(3) + "}},\"block\":\"generated_quantities\"},{\"name\":\"Y_e_rep\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(N) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string(3) + "}},\"block\":\"generated_quantities\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((((((I + I) + 2) + (J * 2)) + J) + 2) + 1)
      + 3);
    const size_t num_transformed = emit_transformed_parameters * (((J + J) +
      J));
    const size_t num_gen_quantities = emit_generated_quantities * (((N + (N *
      3)) + (N * 3)));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((((((I + I) + 2) + (J * 2)) + J) + 2) + 1)
      + 3);
    const size_t num_transformed = emit_transformed_parameters * (((J + J) +
      J));
    const size_t num_gen_quantities = emit_generated_quantities * (((N + (N *
      3)) + (N * 3)));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_ddrm_namespace::model_ddrm;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_ddrm_namespace::profiles__;
}
#endif
#endif
