#' Plot Method for itm_stanfit Objects
#'
#' This function provides a plot method for objects of class `itm_stanfit`.
#'
#' @param x An object of class `itm_stanfit`.
#' @param ... Additional arguments passed to the `plot_consensus` function.
#'
#' @return A plot generated by the `plot_consensus` function.
#'
#' @exportS3Method intervalpsych::plot
#' @noRd
plot.itm_stanfit <- function(x, ...) {
  plot_consensus(x, ...)
}
