#' Plot Method for icm_stanfit Objects
#'
#' This function provides a plot method for objects of class `icm_stanfit`.
#'
#' @param x An object of class `icm_stanfit`.
#' @param ... Additional arguments passed to the `plot_consensus` function.
#'
#' @return A plot generated by the `plot_consensus` function.
#'
#' @examples
#' \dontrun{
#' # Fit ICM model first
#' df_simplex <- data.frame(matrix(runif(100), nrow=10))
#' id_person <- rep(1:5, each=2)
#' id_item <- rep(1:2, times=5)
#' fit <- fit_icm(df_simplex, id_person, id_item)
#' 
#' # Plot using S3 method
#' plot(fit)
#' 
#' # Plot with specific method and parameters
#' plot(fit, method = "draws_distribution", CI = 0.90)
#' }
#'
#' @exportS3Method intervalpsych::plot
plot.icm_stanfit <- function(x, ...) {
  plot_consensus(x, ...)
}
